name: app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter
  
  # Utility Packages
  http: ^0.13.6
  intl: ^0.17.0
  logger: ^2.0.2+1
  url_launcher: ^6.1.11
  flutter_native_splash: ^2.2.17
  smooth_page_indicator: ^1.1.0
  
  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6


  #Products
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2
    

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/on_boarding_images/
    - assets/icons/
    - assets/logos/
    
  fonts:
    # Add assets from the images directory to the application.
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
          
